defaults: &defaults
  posts_on_home_page: 3
  site_name: "Your Site Name"
  site_description: "Description"
  url: http://yoursite.com
  akismet_key: 'YOUR_KEY'
  amazon_s3_key: 'YOUR_KEY'
  amazon_s3_secret_key: 'YOUR_KEY'
  amazon_s3_bucket: 'YOUR_BUCKET'
  amazon_s3_file_location: 'http://s3.amazonaws.com/'
  theme: 'default'
  twitter_account: '@twitter'
  check_spam: true
  # 0 is forever
  comments_open_for_days: 14 
  use_file_based_storage: true #Stop amazons3 being used as a image/document store.
  footer_more_text: "<br /><br />Disclaimer: The opinions expressed herein are my own personal opinions and do not represent my employer's view in any way."
  google_analytics_key: "UA-0000000-0" #Empty string will supress google analytics - ""
  smtp_host: "smtp.yourserver.com"
  smtp_port: "25"
  smtp_user: "user"
  smtp_password: "pass"
  smtp_domain: "yourserver.com"
  site_email: "user@yourserver.com"
  administrator_email: "admin@yourserver.com"
    
development:
  <<: *defaults

test: &test
  posts_on_home_page: 3
  site_name: "Test Site"
  site_description: "Description"
  url: http://192.168.1.68:9393
  akismet_key: '123456789'
  amazon_s3_key: 'NO'
  amazon_s3_secret_key: 'NO'
  amazon_s3_bucket: 'NO'
  amazon_s3_file_location: 'http://s3.amazonaws.com/'
  theme: 'default'
  twitter_account: '@twitter'
  check_spam: false
  comments_open_for_days: 14 
  use_file_based_storage: true
  footer_more_text: "Footer More"
  google_analytics_key: "UA-0000000-0"
  smtp_host: "smtp.yourserver.com"
  smtp_port: "25"
  smtp_user: "user"
  smtp_password: "pass"
  smtp_domain: "yourserver.com"
  site_email: "user@yourserver.com"
  administrator_email: "admin@yourserver.com"

production:
  <<: *defaults
