defaults: &defaults
  posts_on_home_page: "3"
  site_name: "Your Site Name"
  site_description: "Description"
  url: http://yoursite.com
  akismet_key: 'YOUR_KEY'
  amazon_s3_key: 'YOUR_KEY'
  amazon_s3_secret_key: 'YOUR_KEY'
  amazon_s3_bucket: 'YOUR_BUCKET'
  amazon_s3_file_location: 'http://s3.amazonaws.com/'
  theme: 'default'
  twitter_account: '@twitter'
  check_spam: true
  # 0 is forever
  comments_open_for_days:"14" 
  use_file_based_storage: true
      
development:
  <<: *defaults

test: &test
  posts_on_home_page: "3"
  site_name: "Test Site"
  site_description: "Description"
  url: http://192.168.1.68:9393
  akismet_key: '123456789'
  amazon_s3_key: 'NO'
  amazon_s3_secret_key: 'NO'
  amazon_s3_bucket: 'NO'
  amazon_s3_file_location: 'http://s3.amazonaws.com/'
  theme: 'default'
  twitter_account: '@twitter'
  check_spam: false
  comments_open_for_days: "14" 
  use_file_based_storage: true
production:
  <<: *defaults
